#!/usr/bin/python

opened_file = open('/Users/rawr/Library/Mobile Documents/com~apple~CloudDocs/xcode/COVID Python/2020-08-08/2020-08-08.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

#print(apps_data[:1])
#Output of above cmd: [['County', 'OnsetDate', 'Active', 'Deceased', 'Recovered', 'TrendLine']]

counting_counties = {}

for counties in apps_data[1:]:
	if counties[0] in counting_counties:
		counting_counties[counties[0]] += 1
	else:
		counting_counties[counties[0]] = 1

print(counting_counties)
#the above is literally a count of the occurrences of a 'county' in the CSV

#making a list of active cases
active_cases = []
for c_active_index in apps_data[1:]:
	a_cases = int(c_active_index[2])
	active_cases.append(a_cases)
print('There are currently', sum(active_cases), 'active cases in Oklahoma, according to Oklahoma State Department of Health data.')

#making a list of recovered recovered cases
recovered_cases = []
for c_recovered_index in apps_data[1:]:
	r_cases = int(c_recovered_index[4])
	recovered_cases.append(r_cases)
print('There have been', sum(recovered_cases), 'people who have contracted the disease but are no longer infectious.')

dead_cases = []
for c_dead_cases in apps_data[1:]:
	d_cases = int(c_dead_cases[3])
	dead_cases.append(d_cases)
print('Since late March,', sum(dead_cases), 'Oklahomans have died from the disease.')
